sudo: required
services:
  - docker
before_install:
  - docker build -t cobwebfx/docker-go -f Dockerfile.test .
script:
  - docker run cobwebfx/docker-go
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-go"
  env: "DockerGo-env"
  bucket_name: "elasticbeanstalk-us-east-2-366195162601"
  bucket_path: "docker-go"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"