version: '3'
services:
  goapp:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/go/src/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test